import mongoose, { Schema } from "mongoose";

const GRNItemSchema = new Schema({
  sku:       String,
  itemName:  String,
  ordered:   Number,
  received:  Number,
  variance:  Number,
  unit:      String,
  condition: String,
  images:    [String],
  // Reference to the exact PO line (items[]._id, auto-generated by Mongoose)
  // this GRN line was received against, captured at GRN-creation time — lets
  // rate/amount be read back correctly even when a PO has multiple lines
  // sharing the same sku/itemName at different rates (rate-tier splits),
  // where a later sku/name-based lookup would otherwise collapse to the
  // first matching PO line.
  poLineId:  String,
  rate:      Number,
});

const GRNReceiptItemSchema = new Schema({
  sku:      String,
  itemName: String,
  received: Number,
  images:   [String],
  poLineId: String,
  rate:     Number,
}, { _id: false });

const GRNPaymentSchema = new Schema({
  amount:       Number,
  date:         String,
  mode:         String,
  ref:          String,
  utr:          String,
  chequeNo:     String,
  chequeDate:   String,
  screenshotUrl: String,
  bank:         String,
  fromCompany:  String,
  toCompany:    String,
  remarks:      String,
  vendorBankDetails: {
    accountHolder: String,
    bankName:      String,
    accountNo:     String,
    branchIFSC:    String,
  },
}, { _id: false });

const GRNReceiptSchema = new Schema({
  date:          String,
  challan:       String,
  mrNo:          String,
  docType:       String,
  personName:    String,
  challanPhotos: [String],
  personPhotos:  [String],
  items:         [GRNReceiptItemSchema],
  // Per-receipt payment tracking
  paymentStatus: { type: String, enum: ["unpaid", "bill_verified", "bill_approved", "bill_rejected", "mismatch_pending", "payment_pending", "paid"], default: "unpaid" },
  invoiceNo:     String,
  invoiceAmount:   Number,
  freightAmount:   Number,
  loadingAmount:   Number,
  unloadingAmount: Number,
  verifiedBy:    String,
  verifiedById:  String,
  verifiedAt:    String,
  verifyRemark:  String,
  approvedBy:    String,
  approvedAt:    String,
  rejectedBy:    String,
  rejectedAt:    String,
  rejectReason:  String,
  mismatchReason:     String,
  mismatchFlaggedBy:  String,
  mismatchFlaggedById: String,
  mismatchFlaggedAt:  String,
  reVerifyApprovedBy: String,
  reVerifyApprovedAt: String,
  payment:       GRNPaymentSchema,
}, { _id: false });

const GRNSchema = new Schema({
  id:                 { type: String, required: true, unique: true },
  poId:               String,
  project:            String,
  store:              String,
  destinationProject: String,
  supplier:           String,
  date:               String,
  challan:            String,
  mrNo:               String,
  gatePassNo:         String,
  docType:            { type: String, enum: ["Challan","Invoice","Bilty","Gate Pass","Without Challan","Without Gate Pass"] },
  items:              [GRNItemSchema],
  status:             { type: String, enum: ["Draft","Confirmed","Partial","Over-Received","Merged"], default: "Draft" },
  receipts:           { type: [GRNReceiptSchema], default: [] },
  materialImageUrl:   String,
  challanImageUrl:    String,
  challanPhotos:      [String],
  personName:         String,
  personPhotoUrl:     String,
  personPhotos:       [String],
  // Payment tracking (Accounts)
  isLocked:           { type: Boolean, default: false },
  lockedAt:           String,
  paymentStatus:      { type: String, enum: ["unpaid", "bill_verified", "bill_approved", "bill_rejected", "mismatch_pending", "payment_pending", "paid"], default: "unpaid" },
  invoiceNo:          String,
  invoiceAmount:      Number,
  freightAmount:      Number,
  loadingAmount:      Number,
  unloadingAmount:    Number,
  verifiedBy:         String,
  verifiedById:       String,
  verifiedAt:         String,
  verifyRemark:       String,
  approvedBy:         String,
  approvedAt:         String,
  rejectedBy:         String,
  rejectedAt:         String,
  rejectReason:       String,
  mismatchReason:     String,
  mismatchFlaggedBy:  String,
  mismatchFlaggedById: String,
  mismatchFlaggedAt:  String,
  reVerifyApprovedBy: String,
  reVerifyApprovedAt: String,
  payment:            GRNPaymentSchema,
  // Merge tracking — set when this GRN is folded into another
  mergedInto:         { type: String, default: null },
  isActive:           { type: Boolean, default: true },
  // Recycle bin
  isDeleted:  { type: Boolean, default: false },
  deletedAt:  Date,
  deletedBy:  String,
  // Per-SKU qty actually reversed from stock on delete (may be less than the
  // received qty if other stock movement already consumed it) — restore
  // re-applies exactly this amount instead of blindly re-adding received qty,
  // so a clamp during delete can't cause restore to inflate stock.
  deletionReversal: { type: Map, of: Number },
}, { timestamps: true });

GRNSchema.index({ poId: 1 });
GRNSchema.index({ project: 1 });
GRNSchema.index({ supplier: 1 });
GRNSchema.index({ status: 1 });
GRNSchema.index({ mrNo: 1 });
GRNSchema.index({ poId: 1, status: 1 });
GRNSchema.index({ createdAt: -1 });
GRNSchema.index({ updatedAt: -1 });
GRNSchema.index({ paymentStatus: 1 });
GRNSchema.index({ isActive: 1 });
GRNSchema.index({ project: 1, status: 1 });
GRNSchema.index({ store: 1 });
GRNSchema.index({ destinationProject: 1 });

export const GRN = mongoose.model("GRN", GRNSchema);
